{% set name = "preact" %}
{% set version = "8.2.9" %}
{% set sha256 = "ca6938020834bc36032918569e35c81d1a1f3c710c9b047e79ca7570896cf02d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developit/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g preact
  requires:
    - nodejs
   

about:
  home: https://github.com/developit/preact
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast 3kb React alternative with the same ES6 API. Components & Virtual DOM.'
  description: |
    Fast 3kb React alternative with the same ES6 API. Components & Virtual DOM.   
  doc_url: https://preactjs.com/
  dev_url: https://github.com/developit/preact

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
