{% set name = "preact" %}
{% set version = "10.4.5" %}
{% set sha256 = "d185d02a845c11534e274a41036e43fad8f1b77ef9b1fea7b5b65f4a8ffdaa0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developit/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g preact
  requires:
    - nodejs


about:
  home: https://github.com/developit/preact
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast 3kb React alternative with the same ES6 API. Components & Virtual DOM.
  description: |
    Fast 3kb React alternative with the same ES6 API. Components & Virtual DOM.   
  doc_url: https://preactjs.com/
  dev_url: https://github.com/developit/preact
