travis:
  secure:
    BINSTAR_TOKEN: F8No1CLOUlCY809ev+xWE6SG6yexwgYkYOhkfQPMfYuepUHVsHSY123aZnjl8k3IDukhMClKqiJuLEiSmiaYiVALymr5QiycOgMiL5sJ6Pokb7NpMEkKA+lGJUSkiR45egjMdiWkxYzla3zYFpSEC0Gk22CCEk1fWK0VmKkJI/hgLdhoDAGm2ZEXp8v8TQq39HbD/rYnk17N8N7zXoFyPiSMyqwZkOus5AvyWTQL8qRPOu0ocqvlmfO9IKiva9aBMTGdJFmkMz6PkP1pOH2GgPZybgBqbJNYB8ALCrqz5icSH0/LAjlaMonLyJ4FVvOTyA6asD3EUuaXIzYpQ1o2h6aWJlnohJ9ByXyLNlzs/pdGPAlnT0WHGBrwohhAkDzWKSQqM+PT451fWjS1SCLrplK84sNTgD2ureygDESTQQf9sUCF4jSHTp/ZgMRwCwxxZVfHJ4tSrDJC4UPbKgrbCeyDlte8RbSO3mcrQzslBlIuwgwx6y+IuI13wdiKEb+oj5/G5EQLq6mUEotR2gGlqG5aBHPAIehDxpveGqhHaEcqs4S5tyY6psLQnoTtOIYvgfPpdWv2NoGTb6hnMublBd2fWE9xQAOdGhzhvrHePIq2iRQ5Itt5RBvZ4pAY8Pr0eSZ2Ge5bCP3ifZo46NR0DX0zupC+00HrZg8/1Oag1W4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
