travis:
  secure:
    BINSTAR_TOKEN: HcGM7FCfnCBD2Gi678Co+T8xn7pQO5+Na/Tr6ja5lsFGv0Xj87G6nvVofYyo+GNnKjCLLx2T3dLJJTg/RFLUHIAPH9TV3CUfFCghuNQb+SkqOed1kUsqOGKq1IWHlvLJS42C8j29vr+8b37/DmmhAp68TcaIbGdzZbBtXogvjt9Kk+53IsokTP2+IpKnjFG8xm0VL3sMvU5PgEN1lIxfBfItS+i6DIv6BEa2dx54jRv/Yb7LPvMvd718FePXXWvPAsOgXWeW4Wox+CNA8ynFon9BXY1/Bs9uoFIsxgyITnoZSfevFW9NUOLJK2g7uTED0oRER83n+2MmmKIeDF5J2drM9XCJiZKI6ZLeDw2O1gaJkVg1lA/fsRVYhnn9sEY92o1uQnC9kPclVwDsETZrFgaCLsp8r5qM+zjzUECL3oQbr5XNc+xcX4E1Y0xD81kLEagmZwclZ82DoQNzSYcogjKklh4DEeBuhJXmzBHSWEUngzXyVk1F8ELrbfnm/qs/NgGvNuzuxedvVzHcECFwF5MoFgYk5o+ehnU3Yh8r+uxWE5iEHbSIyUAv7Wmp6/kxx16WN/8aru+Wseb5NPm8VZWlP4inyoMCKVX26gyJH9pjN69krHXk+0JTaWx+CKFsDWRum99Z+9Z1WSMFNDNQEWE+CWnSQ8MOy7hFpDCYi/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
