travis:
  secure:
    BINSTAR_TOKEN: pUMclG4ZMsv8WdIDtYOBK9/00IjU5YVGrap0pvZGk4MVNtGhhAq4dNo0cqmMFdxIMD8zy4qlVp5+6j327pyDZf4wSa6GioNn6IMAX2qxh8UJq6hchemcGk67bQB5aI2Xn1I9PVRgqQwPm9Sinw7UQzib4CAORJlFmKhaOBijau2R5pQHAYUa2XrZ2Eqw2b4bnN0LiQgHQz46CI4S0nwuu9m5rnf0PtwQwHQV6Szbv0eJwnOmsCWJqG19PxfRontJ3uil/talSdsokwYrP+vuQ1k9fBUmUKpRIl2kjtSwSyPQlDODWEaIxyV891jg7PJCqqzzrtaUCwU8ypJP3WoDurne6ZYhj5TLdPqOvVWErhNcWyCNuwr2RGOPWZQdG3NgTiEMH9TXRCRgV+tnIL/W2CqXVkOHj5a/ehEmlu2+jnrRBL6ZzaMAuYQ1wV02vjdAUNsnCo1VX4CwgEcTvePAdxC4W+cNwRuuKZOQ4DKRX9y8Pk/wQwvqaW8x/A7rmC9qW3y645+ts5Pmux6SUHmPl5Hx6Cgi4AHw2eAqMMlFGog+i80keOvXSOreSBs2GB84MRZxNbx5DNqaOLoFhqMaoqF963/TndDHn4Vcqijehgoq1G0Am6UPOxoYVDmIafhqiAOGn3/cFTTKGU6AVcGQQYTDtdZMs3lEUgWSP/A92BY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
