travis:
  secure:
    BINSTAR_TOKEN: aYpFtvfot3V1iC44m1kFQSbBAWt4i12JDF7blEMsIkA68v7HxL6V9wfNpVy4b+CzEuBCrZS2rRGaKZMlGUfcqSCrRx3R5EjU/+gtlh2O1TxvgrElQEasr453S1RoQfdRFL6XgIeN8q4LIkSrJ6qYawDXOqm8q5MXLRiazBAseApQ6eD3D4iM+vHiAXQBYdxr5OiI7n3C+89Z/H08sQP5FHtHNx2G2oU3Bf4M3uZrZxkfC9li5EJtACNgxv7WjkTgwKY59xvULejsp8uUrZuzLBzRhrYbT4WbtDeEDy7/XcYkFhJ7JRUtuI/rtIH67+hiBGSNX5Flcy7dgyUECBpzKQOyVaz8tutYjFDWAhPEiIfSuB6P+fGhLlPb61CYqZWtTxKNSnShHAySsRn+x6xYI4odXHVybH+7uE12HMps+Pxd7jIeIwZHYCyQV7aT/aHHFpXhMu2NDsxUF1XdKuYrgCNoipFReEtWhUsI1bE4KmhW3LOwAzTquKJZtATqbM4VKCU/PBVe2HYFBuZeO5A4feKFxVy7+47o2sKKapQ3u5wzD/t7jU+rUeFix/s2jtB9gg1Ar0Ro9mQamxlMJnxGpVVl3TmqZGg8DxyP3sBWgi5FrzJ1jMqR4O5bSuUFCOvX/7MnO8zgE9GNeJn806oHx9yX9xhQFnyP8s7pO+7/qHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
